### ISSUE TITLE
Homecoming Wiki

### ISSUE THREAD

**Issue by damerell** [n15g/badger#30]
There is now a fork of the Paragon Wiki at https://hcwiki.cityofheroes.dev/wiki/Main_Page

We are working on fixing badges which have changed on Homecoming. This is a large task, but I submit that linking to the HC Wiki is at least no worse than linking to the Paragon Wiki for any given badge.

Please, can the links on pages here be changed?

**Comment by n15g** [comment]
I'm moving this over to the homecoming dataset, since that's where the links are actually held.
