### ISSUE TITLE
Have Accolades show what badges are still missing for them

### ISSUE THREAD

**Issue by Betsumei** [n15g/badger#31]
![image](https://user-images.githubusercontent.com/3742052/131918411-0e30568b-8dd5-4174-8e9b-e322d95a099d.png)

Please excuse my inability to draw with a mouse, but here's what I mean. It'd be nice if when viewing the Accolade badges it indicated in some way which of the prerequisites you either have or don't have.

**Comment by n15g** [comment]
I can't believe it doesn't do this already... I'm working on it now!

**Comment by n15g** [comment]
![image](https://user-images.githubusercontent.com/31093750/131924500-ee931ee6-e8a8-45cc-8d11-c746eabe76bf.png)
Collected badges will now appear muted.
