### ISSUE TITLE
Need UX/UI designer

### ISSUE THREAD

**Issue by n15g** [n15g/badger#6]
The current design is pretty boring, and almost standard Bootstrap.

Need someone with UI/UX experience willing to give it a new coat of paint.

**Comment by blhylton** [comment]
Are you married to Bootstrap or was it just convenient at the time? Nothing wrong with it necessarily, I just really hate having to load jQuery into a modern javascript app and Bootstrap relies on it.

**Comment by n15g** [comment]
Mostly familiarity. A big part of the project was wanting to update my skillset... I've worked with Angular JS since it came out, and Bootstrap 3, but haven't had a project to work on the new Angular and bootstrap 4.

If I go ahead with moving the whole thing to a cloud SaaS app, I'll be using react since I haven't had a chance to use it yet, and it seems to be the flavor of the month these days... it'd be a good time to learn a new UI framework too.

I've never really looked into alternatives to bootstrap... the easy responsive support has always made it too convenient to pass up... any suggestions?

**Comment by blhylton** [comment]
I tend to look towards Foundation for anything that doesn't need jQuery.

As for your plans to move to React, I'm actually way more familiar with React than Angular (gave up on Angular after they took 20 years to move from v1 to v2), so let me know and I can help with that.
